map global insert '<c-w>' '<esc>bdi'
map global insert '<c-e>' '<a-;>gl'

# Set the colour scheme
colorscheme tomorrow-night

# Width of a tab
set-option global tabstop 4

# Indent with 4 spaces
set-option global indentwidth 4

# Always keep one line and three columns displayed around the cursor
set-option global scrolloff 1,3

# Display the status bar on top
set-option global ui_options ncurses_status_on_top=true

# Display line numbers
add-highlighter global/ number-lines -relative

# Highlight trailing whitespace
add-highlighter global/ regex \h+$ 0:Error

# Softwrap long lines
add-highlighter global/ wrap -word -indent

# Clipboard management mappings
# map -docstring "yank the selection into the clipboard" global user y "<a-|> xsel -i<ret>"
# map -docstring "paste the clipboard" global user p "<a-!> xsel<ret>"

# Paste from system clipboard
map global user P '!pbpaste<ret>' -docstring 'Paste (before) from system clipboard'
map global user p '<a-!>pbpaste<ret>' -docstring 'Paste (after) from system clipboard'

# For Linux/X11 systems, you would use:
# map global user P '!xclip -selection clipboard -o<ret>' -docstring 'Paste (before) from system clipboard'
# map global user p '<a-!>xclip -selection clipboard -o<ret>' -docstring 'Paste (after) from system clipboard'

# For Wayland:
# map global user P '!wl-paste<ret>' -docstring 'Paste (before) from system clipboard'
# map global user p '<a-!>wl-paste<ret>' -docstring 'Paste (after) from system clipboard'

# Shortcut to quickly exit the editor
define-command -docstring "save and quit" x "write-all; quit"

map global normal '<c-left>' 'gh' -docstring 'previous word'
map global normal '<c-right>' 'gl' -docstring 'next word'

map global insert '<a-left>' '<esc>bi'
map global insert '<a-right>' '<esc>wwi'


# Add backticks to matching pairs
set-option global matching_pairs ( ) [ ] { } < > " " ` ` « »
