# docs to be found at https://beets.readthedocs.io/en/stable/guides/main.html
# install beet: `pipx install beets`
# add external plugins to beets: `pipx inject <venv> <package>`
directory: ~/Music/Albums/
library: ~/.config/beets/library.db
import:
  move: yes
paths:
  default: $albumartist/$album%aunique{}/$track $title # in case of change: `beet move`
plugins: 
  - ftintitle # feature in title (move from artist's field)
  - keyfinder # find music key
  - xtractor  # use models for in-depth analysis, including bpm
  - yearfixer # fix missing year fields
  - follow    # follow artist using muspy. uses deprecated APIs, though…
  - lyrics    # fetch lyrics and write to metadata
  - missing   # lists missing tracks in albums
  # - lastgenre # TO DO using https://github.com/florib779/beets-config/blob/master/config.yaml
ftintitle:
  auto: yes
  drop: no
  format: feat. {0}
keyfinder:
  auto: yes
  bin: keyfinder-cli
  overwrite: no
xtractor: # $ beet xtractor [options] [QUERY...]
    auto: no
    dry-run: no
    write: yes # write bpm analysis to metadata, storethe rest in DB
    threads: 1
    force: no
    quiet: no
    keep_output: yes
    keep_profiles: no
    output_path: /home/antoine/Documents/Experiments/beets/xtractor_data
    essentia_extractor: /usr/bin/essentia_streaming_extractor_music # https://github.com/doctorfree/mpplus-essentia/releases
    extractor_profile:
        highlevel:
            svm_models:
                - /usr/share/mpplus-essentia/svm_models/danceability.history
                - /usr/share/mpplus-essentia/svm_models/gender.history
                - /usr/share/mpplus-essentia/svm_models/genre_rosamerica.history
                - /usr/share/mpplus-essentia/svm_models/mood_acoustic.history
                - /usr/share/mpplus-essentia/svm_models/mood_aggressive.history
                - /usr/share/mpplus-essentia/svm_models/mood_electronic.history
                - /usr/share/mpplus-essentia/svm_models/mood_happy.history
                - /usr/share/mpplus-essentia/svm_models/mood_sad.history
                - /usr/share/mpplus-essentia/svm_models/mood_party.history
                - /usr/share/mpplus-essentia/svm_models/mood_relaxed.history
                - /usr/share/mpplus-essentia/svm_models/voice_instrumental.history
                - /usr/share/mpplus-essentia/svm_models/moods_mirex.history
yearfixer:
  force: no
follow: # this plugin uses deprecated api…
  email: danieldulorens@gmail.com
  password: =S~J8%Ce]fT.PCm
  userid: za6fmz0tued5nu7wkc6saba3a4o1lg
  auto: yes
lyrics:
  auto: yes                  # Fetch lyrics automatically during import. Default: yes.
  fallback: ''               # By default, the file will be left unchanged when no lyrics are found.
                             # Use the empty string '' to reset the lyrics in such a case.
                             # Default: None.
  force: no                  # By default, beets won’t fetch lyrics if the files already have ones.
                             # To instead always fetch lyrics, set the force option to yes.
                             # Default: no.
  #google_API_key: None      # Your Google API key (to enable the Google Custom Search backend).
                             # Default: None.
  #google_engine_ID:         # The custom search engine to use.
                             # Default: The beets custom search engine, which gathers an updated list of sources known to be scrapeable.
  sources:                   # List of sources to search for lyrics.
    - genius                 # genius, google, and tektsowo sources will only be enabled if BeautifulSoup is installed.
    - lyricwiki
    - tekstowo
    - musixmatch             # Possibly just 30% of a whole song text
missing:
    format: $albumartist - $album - $title
    count: no
    total: no
