-- return {
--   -- disable copilot-cmp
--   { "zbirenbaum/copilot-cmp", enabled = false },
--
--   -- keep normal copilot
--   -- {
--   --   "zbirenbaum/copilot.lua",
--   --   cmd = "Copilot",
--   --   event = "InsertEnter",
--   --   config = function()
--   --     require("copilot").setup({})
--   --   end,
--   -- },
-- }
return {}
